use crossterm::event::KeyEvent;
use std::path::PathBuf;
use uuid::Uuid;

use crate::model::profile_organization::MoveDirection;
use crate::profile::ProfileCollection;

use crate::db::catalog_mutation::{
    CatalogMutationCapabilities, CatalogMutationPlan, CatalogMutationRequest,
    CatalogObjectDefinition, CatalogObjectDefinitionRequest, CatalogOwnerContext,
    CatalogOwnerContextRequest,
};
use crate::db::{
    ErrorCategory, ServerInfo,
    catalog::{
        CatalogCapabilities, CatalogDiscovery, CatalogEntry, CatalogId, CatalogPage,
        CatalogRequest, CatalogRequestKey, CatalogSearchPage, CatalogSearchRequest, CatalogTarget,
    },
    catalog_drop::{CatalogDropError, CatalogDropPlan, CatalogDropRequest},
    query::QueryOutcome,
};
use crate::{
    clipboard::ClipboardPayload,
    help::HelpShortcutId,
    model::{
        execution_target::ExecutionTarget,
        explorer::ExplorerNodeId,
        profile_manager::{
            DiscoveryFingerprint, ProfileChange, ProfileField, ProfileInput, ProfileSubmission,
        },
        workspace::{ConnectionIdentity, Focus, PaneLayoutMetrics, PaneResize, PaneSplit},
    },
    persistence::secrets::SecretStoreAvailability,
    profile::{CatalogScope, ConnectionProfile, DatabaseKind},
};

#[derive(Clone, Debug, PartialEq)]
pub enum Action {
    NewConsole,
    NewConsoleNamed(String),
    NewUnboundConsole,
    NewUnboundConsoleNamed(String),
    PrepareActiveConsole,
    OpenDashboard,
    OpenSqlHistory,
    SqlHistoryOpenDetail,
    SqlHistoryBackToBrowse,
    SqlHistoryCopy,
    SqlHistorySelect(usize),
    SqlHistorySearchInsert(char),
    SqlHistorySearchEdit(crate::model::text_input::TextInputEdit),
    SqlHistorySearchPaste(String),
    SqlHistorySearchOpen,
    SqlHistorySearchBackspace,
    SqlHistorySearchClear,
    SqlHistorySearchConfirm,
    SqlHistorySearchCancel,
    SqlHistoryMove(isize),
    SqlHistoryCycleStatus,
    SqlHistoryCycleTransaction,
    SqlHistoryLoadNext,
    SqlHistoryRefresh,
    DashboardSetPage(crate::model::dashboard::DashboardPage),
    DashboardRefresh,
    DashboardTogglePolling,
    DashboardInfoScroll(i16),
    DashboardProcessFilterInsert(char),
    DashboardProcessFilterBackspace,
    DashboardProcessFilterClear,
    DashboardProcessFilterStart,
    DashboardProcessFilterCommit,
    DashboardProcessFilterCancel,
    DashboardProcessFilterDeletePreviousWord,
    DashboardProcessFilterDeleteToStart,
    DashboardProcessFilterDelete,
    DashboardProcessFilterMoveLeft,
    DashboardProcessFilterMoveRight,
    DashboardProcessFilterMoveHome,
    DashboardProcessFilterMoveEnd,
    DashboardProcessFilterUndo,
    DashboardProcessFilterRedo,
    DashboardMetricsDue,
    DashboardProcessesDue,
    CloseActiveTab,
    CloseOtherTabs,
    CloseTab(Uuid),
    RequestDeleteActiveConsole,
    ConfirmDeleteConsole,
    ActivateDeleteConsole,
    CancelDeleteConsole,
    ToggleDeleteConsoleFocus,
    OpenSqlEditorList,
    SqlEditorListMove(isize),
    SqlEditorListActivate,
    SqlEditorListCreate,
    SqlEditorListDeleteRequest,
    SqlEditorListDeleteConfirm,
    SqlEditorListDeleteActivate,
    SqlEditorListDeleteCancel,
    SqlEditorListDeleteFocusNext,
    SqlEditorListDeleteFocusPrevious,
    SqlEditorListSearchStart,
    SqlEditorListRenameStart,
    SqlEditorListRenameCommit,
    SqlEditorListInputInsert(char),
    SqlEditorListInputBackspace,
    SqlEditorListInputDeletePreviousWord,
    SqlEditorListInputDeleteToStart,
    SqlEditorListInputDelete,
    SqlEditorListInputMoveLeft,
    SqlEditorListInputMoveRight,
    SqlEditorListInputMoveHome,
    SqlEditorListInputMoveEnd,
    SqlEditorListInputUndo,
    SqlEditorListInputRedo,
    SqlEditorListCancel,
    ActivateSqlEditor(Uuid),
    NextTab,
    PreviousTab,
    MoveTabRight,
    MoveTabLeft,
    ActivateTab(usize),
    FocusNext,
    FocusPrevious,
    Focus(Focus),
    SmartFocusPane(crate::model::pane_navigation::PaneDirection),
    SmartResizePane(crate::model::pane_navigation::PaneDirection),
    SmartTogglePaneMaximized,
    TogglePaneMaximized,
    ResizePane(PaneResize),
    SetPaneSize {
        split: PaneSplit,
        size: u16,
    },
    ResetPaneSizes,
    PaneLayoutChanged(PaneLayoutMetrics),
    ShowHelp,
    ToggleHelpPanel,
    OpenUpdateCenter,
    StartUpdateCheck {
        automatic: bool,
    },
    UpdateCheckCompleted {
        request_id: u64,
        inspection: crate::update::UpdateInspection,
    },
    UpdateCheckFailed {
        request_id: u64,
        automatic: bool,
        message: String,
    },
    UpdateInstallProgress {
        request_id: u64,
        progress: crate::update::UpdateProgress,
    },
    UpdateOverlayToggleFocus,
    UpdateOverlayConfirm,
    UpdateOverlayActivate(crate::model::update::UpdateDialogAction),
    HelpPanelSettingsWriteFailed(String),
    InstallUpdate,
    UpdateInstalled {
        request_id: u64,
        inspection: crate::update::UpdateInspection,
    },
    UpdateInstallFailed {
        request_id: u64,
        message: String,
    },
    RestartForUpdate,
    DismissOverlay,
    RetryWorkspaceQuitSave,
    DiscardWorkspaceQuitSave,
    WorkspaceSaveFocusNext,
    WorkspaceSaveFocusPrevious,
    WorkspaceSaveActivate,
    WorkspaceSaveActivateAt(usize),
    WorkspaceSaveScroll(isize),
    ToggleTerminalSelection,
    DismissNotification(u64),
    OpenNotificationHistory,
    OpenNotificationHistoryAt(u64),
    NotificationHistorySearchOpen,
    NotificationHistorySearchInsert(char),
    NotificationHistorySearchBackspace,
    NotificationHistorySearchClear,
    NotificationHistorySearchUndo,
    NotificationHistorySearchRedo,
    NotificationHistorySearchConfirm,
    NotificationHistorySearchCancel,
    NotificationHistoryNext,
    NotificationHistoryPrevious,
    NotificationHistoryMove(isize),
    NotificationHistoryPage(isize),
    NotificationHistoryJump(bool),
    NotificationHistorySelect(usize),
    NotificationHistoryOpenDetail,
    NotificationHistoryCopy,
    NotificationDetailMove(isize),
    NotificationDetailCopy,
    NotificationDetailClose,
    NotificationHistoryClear,
    NotificationHistoryClearConfirm,
    NotificationHistoryClearCancel,
    HelpEdit(crate::model::text_input::TextInputEdit),
    HelpPaste(String),
    HelpMove(isize),
    HelpSelect(usize),
    HelpScroll(isize),
    HelpSetScroll(usize),
    HelpViewportChanged(usize),
    ExecuteHelpShortcut(HelpShortcutId),
    OpenOmni,
    OmniEdit(crate::model::text_input::TextInputEdit),
    OmniPaste(String),
    OmniMove(isize),
    OmniSelect(usize),
    OmniScroll(isize),
    OmniSetScroll(usize),
    OmniViewportChanged(usize),
    OmniConfirm,
    OmniCancel,
    OmniDismiss,
    OmniShowActions,
    OmniResumeInteraction(Uuid),
    ExecuteSemanticCommand {
        id: crate::commands::CommandId,
        context: crate::commands::CommandContext,
    },
    SubstituteYes,
    SubstituteNo,
    SubstituteAll,
    SubstituteLast,
    SubstituteQuit,
    OpenProfileManager,
    SystemCredentialAvailability(SecretStoreAvailability),
    CloseProfileManager,
    ProfileStartNew,
    ProfileStartEdit {
        profile_id: Uuid,
    },
    OpenExplorerAdd,
    ExplorerAddMove(isize),
    ExplorerAddSelect(usize),
    ExplorerAddConfirm,
    ExplorerAddCancel,
    OpenCatalogCreate,
    OpenCatalogEdit,
    ProfileRequestDelete {
        profile_id: Uuid,
    },
    RequestDropCatalogObject {
        id: crate::db::catalog::CatalogId,
    },
    OpenPrincipalDrop,
    PrincipalDropPlanReady(crate::db::principal_drop::PrincipalDropPlan),
    PrincipalDropPlanFailed {
        request: crate::db::principal_drop::PrincipalDropRequest,
        message: String,
    },
    PrincipalDropCancel,
    PrincipalDropConfirm,
    PlanPrincipalMutation {
        request: crate::db::principal::PrincipalMutationRequest,
    },
    PrincipalMutationPlanReady(crate::db::principal::PrincipalMutationPlan),
    PrincipalMutationPlanFailed {
        request: crate::db::principal::PrincipalMutationRequest,
        message: String,
    },
    ExecutePrincipalMutation(crate::db::principal::PrincipalMutationPlan),
    PrincipalMutationSucceeded {
        plan: crate::db::principal::PrincipalMutationPlan,
    },
    PrincipalMutationFailed {
        plan: crate::db::principal::PrincipalMutationPlan,
        message: String,
    },
    TogglePrincipalDropFocus,
    PrincipalDropSucceeded {
        plan: crate::db::principal_drop::PrincipalDropPlan,
    },
    PrincipalDropFailed {
        plan: crate::db::principal_drop::PrincipalDropPlan,
        message: String,
    },
    CatalogDropPlanReady(CatalogDropPlan),
    CatalogDropPlanFailed {
        request: CatalogDropRequest,
        error: CatalogDropError,
    },
    CatalogDropSucceeded {
        plan: CatalogDropPlan,
        outcome: QueryOutcome,
    },
    CatalogDropFailed {
        plan: CatalogDropPlan,
        message: String,
    },
    CatalogMutationPlanReady(CatalogMutationPlan),
    CatalogMutationPlanFailed {
        request: CatalogMutationRequest,
        message: String,
    },
    CatalogMutationSucceeded {
        plan: CatalogMutationPlan,
        outcome: QueryOutcome,
    },
    CatalogMutationFailed {
        plan: CatalogMutationPlan,
        message: String,
    },
    CatalogObjectDefinitionLoaded {
        request: CatalogObjectDefinitionRequest,
        definition: CatalogObjectDefinition,
    },
    CatalogObjectDefinitionLoadFailed {
        request: CatalogObjectDefinitionRequest,
        message: String,
    },
    CatalogOwnerContextLoaded {
        request: CatalogOwnerContextRequest,
        context: CatalogOwnerContext,
    },
    CatalogOwnerContextLoadFailed {
        request: CatalogOwnerContextRequest,
        message: String,
    },
    ToggleCatalogDropFocus,
    ActivateCatalogDrop,
    CatalogDropConfirm,
    CatalogDropCancel,
    CatalogDropMaintenanceInsert(char),
    CatalogDropMaintenanceBackspace,
    CatalogDropMaintenanceClear,
    CatalogEditorCancel,
    CatalogEditorDiscardMove(isize),
    CatalogEditorDiscardKeepEditing,
    CatalogEditorDiscardChanges,
    CatalogEditorMove(isize),
    CatalogEditorSelect,
    CatalogEditorFieldNext,
    CatalogEditorFieldPrevious,
    CatalogEditorFocusField(usize),
    CatalogEditorFocusFormField(crate::model::catalog_editor::CatalogFormFocus),
    CatalogOwnerPickerOpen,
    CatalogOwnerPickerClose,
    CatalogOwnerPickerMove(isize),
    CatalogOwnerPickerInsert(char),
    CatalogOwnerPickerBackspace,
    CatalogOwnerPickerDeletePreviousWord,
    CatalogOwnerPickerDeleteToStart,
    CatalogOwnerPickerUndo,
    CatalogOwnerPickerRedo,
    CatalogOwnerPickerAccept,
    CatalogOwnerPickerChoose(String),
    CatalogEditorInsert(char),
    CatalogEditorPaste(String),
    CatalogEditorBackspace,
    CatalogEditorDeletePreviousWord,
    CatalogEditorDeleteToStart,
    CatalogEditorDelete,
    CatalogEditorMoveLeft,
    CatalogEditorMoveRight,
    CatalogEditorMoveHome,
    CatalogEditorMoveEnd,
    CatalogEditorUndo,
    CatalogEditorRedo,
    CatalogEditorCycleChoice(isize),
    CatalogEditorToggleFocused,
    CatalogEditorPreview,
    CatalogEditorApply,
    CatalogEditorBack,
    CatalogEditorPreviewScroll(isize),
    CatalogEditorPreviewHome,
    CatalogEditorPreviewEnd,
    CatalogEditorConfirmInsert(char),
    CatalogEditorConfirmBackspace,
    CatalogEditorConfirmUndo,
    CatalogEditorConfirmRedo,
    CatalogEditorFocusTableField(crate::model::catalog_editor::TableEditorFocus),
    CatalogEditorSetCursor {
        target: crate::action::CatalogEditorCursorTarget,
        cursor: usize,
    },
    CatalogEditorSelectTableColumn(usize),
    CatalogEditorOpenTableColumnDetails,
    CatalogEditorConfirmTableColumnDetails,
    CatalogEditorCancelTableColumnDetails,
    CatalogEditorMoveTableColumn(isize),
    CatalogEditorAddTableColumn,
    CatalogEditorAddTableColumnAbove,
    CatalogEditorReorderTableColumn(isize),
    CatalogEditorRemoveTableColumn,
    CatalogEditorRestoreTableColumn,
    CatalogEditorRemoveTableColumnRow(uuid::Uuid),
    CatalogEditorRestoreTableColumnRow(uuid::Uuid),
    CatalogEditorToggleTableColumnNullable,
    CatalogEditorToggleTableColumnIdentity,
    OpenRedisObjectCreate,
    OpenRedisObjectCreateAt {
        profile_id: Uuid,
        database: u32,
    },
    OpenRedisObjectEdit,
    RedisObjectEditorCancel,
    RedisObjectEditorFocusNext,
    RedisObjectEditorFocusPrevious,
    RedisObjectEditorInsert(char),
    RedisObjectEditorPaste(String),
    RedisObjectEditorBackspace,
    RedisObjectEditorDeletePreviousWord,
    RedisObjectEditorDeleteToStart,
    RedisObjectEditorDelete,
    RedisObjectEditorMoveLeft,
    RedisObjectEditorMoveRight,
    RedisObjectEditorMoveHome,
    RedisObjectEditorMoveEnd,
    RedisObjectEditorUndo,
    RedisObjectEditorRedo,
    RedisObjectEditorCycleType(isize),
    RedisObjectEditorCycleTtl(isize),
    RedisObjectEditorApply,
    ProfileConfirmDelete,
    ActivateProfileDelete,
    ProfileCancelDelete,
    ToggleProfileDeleteFocus,
    ProfileFieldNext,
    ProfileFieldPrevious,
    ProfileFocusField(ProfileField),
    ProfileSetCursor {
        field: ProfileField,
        cursor: usize,
    },
    ProfileInsert(ProfileInput),
    ProfilePaste(ProfileInput),
    ProfileBackspace,
    ProfileDeletePreviousWord,
    ProfileDeleteToStart,
    ProfileDeleteCharacter,
    ProfileMoveLeft,
    ProfileMoveRight,
    ProfileMoveHome,
    ProfileMoveEnd,
    ProfileUndo,
    ProfileRedo,
    ProfileCommitUrl,
    ProfileCycle(i8),
    ProfileSelectDriver(DatabaseKind),
    ProfileSelectCategory(crate::db::descriptor::DatabaseCategory),
    ProfileToggle,
    ProfileToggleField(ProfileField),
    ProfileOpenScope,
    ProfileRefreshScope,
    ProfileToggleScopeRow(String),
    ProfileScopeMove(isize),
    ProfileScopeBack,
    ProfileTest,
    ProfileSave {
        connect: bool,
    },
    ProfileTestSucceeded {
        request_id: u64,
        fingerprint: DiscoveryFingerprint,
        server: ServerInfo,
        capabilities: CatalogCapabilities,
        discovery: Option<Result<CatalogDiscovery, String>>,
    },
    ProfileTestFailed {
        request_id: u64,
        message: String,
    },
    ProfileCatalogDiscoverySucceeded {
        request_id: u64,
        fingerprint: DiscoveryFingerprint,
        server: ServerInfo,
        capabilities: CatalogCapabilities,
        discovery: CatalogDiscovery,
    },
    ProfileCatalogDiscoveryFailed {
        request_id: u64,
        fingerprint: DiscoveryFingerprint,
        message: String,
    },
    ProfileSaved {
        request_id: u64,
        profile: ConnectionProfile,
        warning: Option<String>,
        change: ProfileChange,
        connect: bool,
    },
    ProfileSaveFailed {
        request_id: u64,
        message: String,
    },
    OpenProfileAccess,
    ProfileAccessMove(isize),
    ProfileAccessConfirm,
    ProfileAccessCancel,
    ProfileGroupOpen,
    ProfileGroupCreate,
    ProfileGroupMove(isize),
    ProfileGroupSelect(usize),
    ProfileGroupEdit(crate::model::text_input::TextInputEdit),
    ProfileGroupConfirm,
    ProfileGroupCancel,
    ProfileGroupDeleteConfirm,
    ToggleProfileGroupDeleteFocus,
    ProfileAccessUpdated {
        request_id: u64,
        profile_id: Uuid,
        access: crate::profile::ProfileAccess,
    },
    ProfileAccessUpdateFailed {
        request_id: u64,
        profile_id: Uuid,
        message: String,
    },
    ProfileDeleted {
        request_id: u64,
        profile_id: Uuid,
        active_connection: Option<ConnectionIdentity>,
    },
    ProfileDeleteFailed {
        request_id: u64,
        message: String,
    },
    ProfileOrganizationSaved {
        request_id: u64,
        collection: ProfileCollection,
    },
    ProfileOrganizationSaveFailed {
        request_id: u64,
        message: String,
    },
    CredentialsRequired {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    DisconnectCompleted {
        connection: ConnectionIdentity,
    },
    ReplaceEditor(String),
    EditorKey(KeyEvent),
    ReadOnlyEditorKey {
        session_id: Uuid,
        event: KeyEvent,
    },
    ReadOnlyEditorScroll {
        session_id: Uuid,
        rows: isize,
        columns: isize,
    },
    EditorPaste(String),
    CopyEditorYank(String),
    CopyEditorSelection {
        session_id: Uuid,
        start: crate::model::editor::EditorPosition,
        end: crate::model::editor::EditorPosition,
        revision: u64,
    },
    CompleteMouseTextSelection {
        source: crate::ui::text_selection::TextGestureSource,
        session_id: Uuid,
        start: crate::model::editor::EditorPosition,
        end: crate::model::editor::EditorPosition,
        revision: u64,
    },
    CompleteMouseInputSelection {
        target: crate::ui::text_selection::InputSelectionTarget,
        start: usize,
        end: usize,
    },
    BeginMouseInputSelection {
        target: crate::ui::text_selection::InputSelectionTarget,
        cursor: usize,
    },
    UpdateMouseInputSelection {
        target: crate::ui::text_selection::InputSelectionTarget,
        cursor: usize,
    },
    CancelMouseInputSelection {
        target: crate::ui::text_selection::InputSelectionTarget,
    },
    SetEditorMouseCursor {
        session_id: Uuid,
        position: crate::model::editor::EditorPosition,
        revision: u64,
    },
    CopyEditorStatement,
    CopyEditorBuffer,
    CopyGridCell,
    CopyPrincipalAccess,
    CopyGridRow {
        include_headers: bool,
    },
    ViewGridCell,
    CopyRecordViewCell,
    CopyRecordViewRow {
        include_headers: bool,
    },
    ViewRecordViewValue,
    ClipboardWritten {
        description: String,
    },
    ClipboardWriteFailed {
        message: String,
    },
    Osc52Clipboard {
        payload: ClipboardPayload,
    },
    EditorViewportChanged(crate::model::editor::EditorViewport),
    OutputViewportChanged {
        session_id: Uuid,
        viewport: crate::model::editor::EditorViewport,
    },
    TransactionReviewEditorViewportChanged {
        session_id: Uuid,
        viewport: crate::model::editor::EditorViewport,
    },
    EditorScroll {
        rows: isize,
        columns: isize,
    },
    EditorSetScroll {
        session_id: Uuid,
        rows: isize,
        columns: isize,
    },
    EditorSetScrollAxis {
        session_id: Uuid,
        vertical: bool,
        offset: usize,
    },
    EditorScrollBy {
        session_id: Uuid,
        rows: isize,
        columns: isize,
    },
    CompletionDue(crate::sql::CompletionScheduleKey),
    DiagnosticDue(crate::sql::DiagnosticScheduleKey),
    DiagnosticsReady {
        key: crate::sql::DiagnosticScheduleKey,
        diagnostics: Vec<crate::sql::SqlDiagnostic>,
        dependencies: Vec<crate::db::catalog::CatalogId>,
    },
    CompletionExplicit,
    CompletionNext,
    CompletionPrevious,
    CompletionAccept,
    CompletionDismiss,
    RunActiveSql,
    RunAllSql,
    ConfirmExecution,
    CancelExecution,
    ToggleExecutionConfirmationFocus,
    ConfirmPrincipalMutation,
    CancelPrincipalMutation,
    TogglePrincipalMutationFocus,
    ScrollExecutionConfirmation {
        rows: isize,
    },
    ScrollRelationTransactionReview {
        rows: isize,
    },
    TransactionReviewFocusNext,
    TransactionReviewFocusPrevious,
    TransactionReviewMoveButton(isize),
    TransactionReviewFocusPreview,
    TransactionReviewPromptPaste(String),
    CancelActiveQuery,
    ConfirmManualCancellation,
    CancelManualCancellation,
    ToggleManualCancellationFocus,
    ActivateManualCancellationKeepRunning,
    ConfirmTransactionExit,
    ConfirmTransactionExitChoice(crate::model::transaction::TransactionExitChoice),
    CancelTransactionExit,
    ToggleTransactionExitChoice,
    TogglePreviousTransactionExitChoice,
    ConfirmClearTransactionOutcome,
    CancelClearTransactionOutcome,
    ToggleClearTransactionOutcomeFocus,
    OpenTargetSelector,
    OpenConsoleTargetSelector {
        console_id: Uuid,
    },
    OpenDatabaseSelector,
    SelectDatabaseSelector(usize),
    MoveDatabaseSelector(isize),
    ConfirmDatabaseSelector,
    CancelDatabaseSelector,
    SelectTargetSelector(usize),
    MoveTargetSelector(isize),
    ConfirmTargetSelector,
    CancelTargetSelector,
    SetTransactionMode(crate::model::transaction::TransactionMode),
    ActivateEditorTransaction,
    OpenTransactionControl,
    OpenTransactionMenu,
    SelectTransactionMenu(usize),
    MoveTransactionMenu(isize),
    ConfirmTransactionMenu,
    CancelTransactionMenu,
    CommitTransaction,
    RollbackTransaction,
    ClearTransactionOutcome,
    RefreshCatalog,
    ExplorerLoadTarget(CatalogTarget),
    ExplorerOpenSelected,
    OpenSelectedRelation {
        view: crate::model::relation::RelationView,
    },
    OpenCatalogRelation {
        id: crate::db::catalog::CatalogId,
        view: crate::model::relation::RelationView,
    },
    SetRelationView(crate::model::relation::RelationView),
    SetResultView(crate::model::tab::ResultView),
    RefreshActiveRelation,
    RelationFirstPage,
    RelationPreviousPage,
    RelationNextPage,
    RelationLastPage,
    SetRelationPageSize(crate::model::pagination::PageSize),
    ResultFirstPage,
    ResultPreviousPage,
    ResultNextPage,
    ResultLastPage,
    SetResultPageSize(crate::model::pagination::PageSize),
    OpenPageSizeSelector {
        relation: bool,
    },
    MovePageSizeSelector(isize),
    ConfirmPageSizeSelector,
    CancelPageSizeSelector,
    CancelActiveRelationRequest,
    OpenPrincipal {
        profile_id: Uuid,
        entry: crate::db::principal::PrincipalEntry,
    },
    RefreshActivePrincipal,
    SetPrincipalView(crate::model::principal::PrincipalView),
    OpenPrincipalPermissionMutation {
        grant: bool,
    },
    ConfirmPrincipalMutationForm,
    CancelPrincipalMutationForm,
    TogglePrincipalMutationFormField,
    TogglePrincipalMutationFormOption,
    TogglePrincipalMutationFormOperation,
    SelectPrincipalPermission(usize),
    MovePrincipalPermission(isize),
    SelectPrincipalAccess(crate::model::principal::PrincipalAccessSection),
    MovePrincipalAccess(isize),
    PrincipalAccessSelectFirst,
    PrincipalAccessSelectLast,
    PagePrincipalAccess {
        direction: isize,
        half_page: bool,
    },
    ScrollPrincipalAccess(isize),
    SetPrincipalAccessOffset(usize),
    PrincipalAccessViewportChanged {
        tab_id: Uuid,
        rows: usize,
    },
    PrincipalAccessFindOpen,
    PrincipalAccessFindEdit(crate::model::text_input::TextInputEdit),
    PrincipalAccessFindConfirm,
    PrincipalAccessFindNext,
    PrincipalAccessFindPrevious,
    PrincipalAccessFindClose,
    SelectPrincipalAccessItem(usize),
    OpenPrincipalAccessDetails,
    PrincipalMutationFieldNext,
    PrincipalMutationToggleOperation,
    PrincipalMutationToggleOption,
    CancelActivePrincipalRequest,
    PrincipalPageLoaded {
        profile_id: Uuid,
        request_id: u64,
        page: crate::db::principal::PrincipalPage,
    },
    PrincipalPageFailed {
        profile_id: Uuid,
        request_id: u64,
        message: String,
    },
    PrincipalDdlLoaded {
        request: crate::model::principal::PrincipalDdlRequest,
        ddl: crate::db::principal::PrincipalDdl,
    },
    PrincipalDetailsLoaded {
        request: crate::model::principal::PrincipalDetailsRequest,
        details: crate::db::principal::PrincipalDetails,
    },
    PrincipalDetailsFailed {
        request: crate::model::principal::PrincipalDetailsRequest,
        message: String,
    },
    PrincipalDdlFailed {
        request: crate::model::principal::PrincipalDdlRequest,
        message: String,
    },
    DdlScroll {
        rows: isize,
        columns: isize,
    },
    DdlScrollToStart,
    DdlScrollToEnd,
    SetDdlViewportMetrics {
        visible_rows: usize,
        visible_columns: usize,
        total_rows: usize,
        max_line_width: usize,
    },
    DdlEditorViewportChanged {
        session_id: Uuid,
        viewport: crate::model::editor::EditorViewport,
    },
    FocusDataQueryInput(crate::model::data_query::DataQueryInput),
    SetDataQueryCursor {
        input: crate::model::data_query::DataQueryInput,
        cursor: usize,
    },
    DataQueryInsert(char),
    DataQueryBackspace,
    DataQueryDeletePreviousWord,
    DataQueryDeleteToStart,
    DataQueryDelete,
    DataQueryMoveLeft,
    DataQueryMoveRight,
    DataQueryMoveHome,
    DataQueryMoveEnd,
    DataQueryClear,
    DataQueryUndo,
    DataQueryRedo,
    DataQueryCompletionNext,
    DataQueryCompletionPrevious,
    DataQueryCompletionAccept,
    DataQueryCompletionDismiss,
    SubmitDataQuery,
    CancelDataQueryInput,
    // Kept as reducer aliases for callers using the pre-shared relation names.
    FocusRelationQueryInput(crate::model::relation::RelationQueryInput),
    RelationQueryInsert(char),
    RelationQueryBackspace,
    RelationQueryDelete,
    RelationQueryMoveLeft,
    RelationQueryMoveRight,
    RelationQueryMoveHome,
    RelationQueryMoveEnd,
    RelationQueryClear,
    SubmitRelationQuery,
    CancelRelationQueryInput,
    CycleDataColumnSort(usize),
    ResizeRelationColumn(i16),
    ResetRelationColumnWidth,
    StartRelationColumnResize {
        column: usize,
        width: u16,
    },
    SetRelationColumnWidth {
        column: usize,
        width: u16,
    },
    EndRelationColumnResize,
    GridResizeColumn(i16),
    GridResetColumnWidth,
    GridStartColumnResize {
        column: usize,
        width: u16,
    },
    GridSetColumnWidth {
        column: usize,
        width: u16,
    },
    GridEndColumnResize,
    GridSetColumnOffset {
        offset: usize,
    },
    GridSetRowOffset {
        offset: usize,
    },
    GridScrollColumns {
        offset: usize,
        first_visible: usize,
        last_visible: usize,
    },
    RelationEditCell,
    RelationEditBooleanMove(isize),
    RelationEditBooleanToggle,
    RelationEditBooleanSet(bool),
    RelationEditSetNull,
    RelationEditRestoreDefault,
    RelationEditUseValue,
    RelationEditTemporalMove(isize),
    RelationEditTemporalMonth(isize),
    RelationEditInsert(char),
    RelationEditJsonFormat,
    RelationEditJsonMove(isize),
    RelationEditBackspace,
    RelationEditDeletePreviousWord,
    RelationEditDeleteToStart,
    RelationEditDelete,
    RelationEditMoveLeft,
    RelationEditMoveRight,
    RelationEditMoveHome,
    RelationEditMoveEnd,
    RelationEditUndo,
    RelationEditRedo,
    RelationEditConfirm,
    RelationEditCancel,
    RelationVisualLine,
    RelationDeleteCurrent,
    RelationDeleteSelected,
    RelationYank,
    RelationYankSelected,
    RelationPaste,
    RelationInsertRow,
    RelationUndo,
    RelationRedo,
    RelationCommit,
    RelationRollback,
    PreviewSelected,
    DdlSelected,
    RelationSucceeded {
        request: crate::model::relation::RelationRequest,
        snapshot: Box<crate::model::relation::RelationSnapshot>,
    },
    RelationFailed {
        request: crate::model::relation::RelationRequest,
        message: String,
    },
    RelationTransactionStarted {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    RelationTransactionStartFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    RelationMutationSucceeded {
        request: crate::db::mutation::RelationMutationRequest,
        result: crate::db::mutation::MutationResult,
    },
    RelationMutationFailed {
        request: crate::db::mutation::RelationMutationRequest,
        message: String,
        diagnostic: Option<crate::db::transaction::RelationMutationDiagnostic>,
    },
    RelationCommitted {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    RelationCommitFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    RelationRolledBack {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    RelationRollbackFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    RequestProfileConnect {
        profile_id: Uuid,
    },
    RequestConnect(Uuid),
    RetryActiveConsoleConnection,
    RequestProfileDisconnect {
        profile_id: Uuid,
    },
    ConnectionSucceeded {
        profile_id: Uuid,
        generation: u64,
        server: ServerInfo,
        mutation_capabilities: CatalogMutationCapabilities,
    },
    ConnectionFailed {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    ConnectionInvalidated {
        connection: ConnectionIdentity,
        message: String,
    },
    CatalogPageLoaded(CatalogPage),
    CatalogPageFailed {
        key: CatalogRequestKey,
        category: ErrorCategory,
        message: String,
    },
    RedisDatabasesLoaded {
        profile_id: Uuid,
        generation: u64,
        discovery: crate::db::redis::discovery::RedisDatabaseDiscovery,
    },
    RedisDatabasesFailed {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    RedisKeysLoaded(crate::db::redis::types::KeyScanBatch),
    RedisKeysFailed {
        identity: crate::db::redis::types::RedisRequestIdentity,
        message: String,
    },
    RedisKeyDeleted {
        tab_id: Uuid,
        key: crate::db::redis::types::RedisKeyId,
    },
    RedisKeyDeleteFailed {
        tab_id: Uuid,
        key: crate::db::redis::types::RedisKeyId,
        message: String,
    },
    RedisPreviewLoaded {
        tab_id: Uuid,
        generation: u64,
        preview_generation: u64,
        key: crate::db::redis::types::RedisKeyId,
        content: String,
    },
    RedisPreviewFailed {
        tab_id: Uuid,
        generation: u64,
        preview_generation: u64,
        key: crate::db::redis::types::RedisKeyId,
        message: String,
    },
    RedisValuePageLoaded {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        preview_generation: u64,
        page: crate::db::redis::read::RedisValuePage,
    },
    RedisValuePageFailed {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        preview_generation: u64,
        key: crate::db::redis::types::RedisKeyId,
        message: String,
    },
    RedisValuePageFormatted {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        preview_generation: u64,
        format: crate::value_preview::PreviewFormat,
        page: crate::db::redis::read::RedisValuePage,
        result: Result<String, String>,
    },
    RedisMutationPlanReady(crate::db::redis::mutation::RedisMutationPlan),
    RedisMutationPlanFailed {
        request: crate::db::redis::mutation::RedisMutationRequest,
        message: String,
    },
    RedisMutationSucceeded {
        plan: crate::db::redis::mutation::RedisMutationPlan,
        result: crate::db::redis::mutation::RedisMutationResult,
    },
    RedisMutationFailed {
        plan: crate::db::redis::mutation::RedisMutationPlan,
        message: String,
    },
    CatalogRelationResolved {
        connection: ConnectionIdentity,
        catalog_epoch: u64,
        request_id: u64,
        relation: CatalogId,
        entry: Option<CatalogEntry>,
    },
    CatalogRelationResolutionFailed {
        connection: ConnectionIdentity,
        catalog_epoch: u64,
        request_id: u64,
        relation: CatalogId,
        category: ErrorCategory,
        message: String,
    },
    CatalogSearchSucceeded {
        owner: CatalogSearchOwner,
        page: CatalogSearchPage,
    },
    CatalogSearchFailed {
        owner: CatalogSearchOwner,
        connection: ConnectionIdentity,
        session_id: u64,
        generation: u64,
        message: String,
    },
    QueryFinished {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
    },
    DashboardMetricsLoaded {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        snapshot: crate::db::monitor::MonitorSnapshot,
    },
    DashboardMetricsFailed {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    DashboardMetadataLoaded {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        metadata: crate::db::monitor::MonitorMetadata,
    },
    DashboardMetadataFailed {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    DashboardProcessesLoaded {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        snapshot: crate::db::monitor::ProcessSnapshot,
    },
    DashboardProcessesFailed {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    QueryFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    SqlHistoryLoaded {
        overlay_id: Uuid,
        generation: u64,
        page: crate::persistence::sql_history::HistoryPage,
    },
    SqlHistoryLoadFailed {
        overlay_id: Uuid,
        generation: u64,
        message: String,
    },
    QueryPageFinished {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
        pagination: crate::model::pagination::ResultPagination,
    },
    QueryPageFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    DerivedQueryFinished {
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        outcome: QueryOutcome,
    },
    DerivedQueryPageFinished {
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        outcome: QueryOutcome,
        pagination: crate::model::pagination::ResultPagination,
    },
    DerivedQueryFailed {
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        message: String,
    },
    DerivedQueryPageFailed {
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        message: String,
    },
    ManualStarted {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualStartFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualQueryFinished {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
    },
    ManualQueryPageFinished {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
        pagination: crate::model::pagination::ResultPagination,
    },
    ManualQueryFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualQueryPageFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualImplicitlyEnded {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualCommitted {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualCommitFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    ManualRolledBack {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualRollbackFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    ExplorerMove(isize),
    ExplorerViewportChanged(usize),
    ExplorerSelectTarget(crate::model::explorer::ExplorerNodeTarget),
    ExplorerScrollNodes {
        direction: isize,
        amount: crate::model::explorer::ExplorerScrollAmount,
    },
    ExplorerSetScrollOffset(usize),
    ExplorerAlignSelected(crate::model::explorer::ExplorerNodeAlignment),
    ExplorerFindOpen,
    ExplorerFindInsert(char),
    ExplorerFindBackspace,
    ExplorerFindClear,
    ExplorerFindUndo,
    ExplorerFindRedo,
    ExplorerFindConfirm,
    ExplorerFindNext,
    ExplorerFindPrevious,
    ExplorerFindClose,
    ExplorerSearchOpen,
    ExplorerSearchInsert(char),
    ExplorerSearchBackspace,
    ExplorerSearchClear,
    ExplorerSearchUndo,
    ExplorerSearchRedo,
    ExplorerSearchMove(isize),
    ExplorerSearchNext,
    ExplorerSearchPrevious,
    ExplorerSearchLocate,
    ExplorerSearchClose,
    ExplorerSearchRetry,
    ExplorerSelect(ExplorerNodeId),
    ExplorerToggleNode(ExplorerNodeId),
    CopyExplorerSelection,
    ExplorerToggle,
    ExplorerExpand,
    ExplorerCollapse,
    ExplorerPrimary,
    ExplorerRefresh,
    OpenRedisDatabase {
        profile_id: Uuid,
        database: u32,
    },
    SelectRedisNode {
        tab_id: Uuid,
        node: Option<crate::model::redis_key_tree::KeyTreeNodeId>,
    },
    OpenRedisKey {
        tab_id: Uuid,
        node: crate::model::redis_key_tree::KeyTreeNodeId,
    },
    RedisToggleNode {
        tab_id: Uuid,
        node: crate::model::redis_key_tree::KeyTreeNodeId,
    },
    RedisMoveSelection(isize),
    RedisExpandSelection,
    RedisCollapseSelection,
    RedisPrimarySelection,
    RedisCopyKey,
    RedisDeleteKey,
    RedisDeleteConfirm,
    RedisDeleteCancel,
    RedisDeleteToggleFocus,
    RedisDeletePrepared {
        tab_id: Uuid,
        target: crate::model::workspace::RedisDeleteTarget,
        keys: Vec<Vec<u8>>,
    },
    RedisDeleteBatchCompleted {
        tab_id: Uuid,
        target: crate::db::redis::types::RedisTarget,
        keys: Vec<Vec<u8>>,
        deleted: usize,
        missing: usize,
        failed: Option<String>,
    },
    RedisFocusPane(crate::model::redis_browser::RedisBrowserFocus),
    RedisKeysViewportChanged {
        tab_id: Uuid,
        rows: usize,
    },
    RedisKeysScroll(isize),
    RedisPreviewScroll(isize),
    RedisPreviewCycleFormat,
    RedisPreviewToggleWrap,
    RedisPreviewFormatMove(isize),
    RedisPreviewFormatAccept,
    RedisPreviewFormatCancel,
    RedisPreviewLoadNext,
    RedisPreviewTick,
    RedisPreviewCellDetail {
        tab_id: Uuid,
        row: usize,
        column: usize,
    },
    /// Opens the native Redis value editor for the selected table cell/row.
    /// The current editor uses the same typed page as the preview and keeps
    /// the action distinct from relation-table transactions.
    RedisPreviewEdit,
    RedisPreviewAdd,
    RedisPreviewDelete,
    RedisValueSave,
    RedisValueSaveAnyway,
    RedisValueSaveCancel,
    RedisValueSaveToggleFocus,
    RedisValueSaveActivate(usize),
    RedisUnsavedValueSave,
    RedisUnsavedValueDiscard,
    RedisUnsavedValueCancel,
    RedisUnsavedValueToggleFocus,
    RedisUnsavedValueActivate(usize),
    RedisTableDeleteConfirm,
    RedisTableDeleteCancel,
    RedisTableDeleteToggleFocus,
    RedisPreviewViewportChanged {
        tab_id: Uuid,
        rows: usize,
        content_rows: usize,
    },
    RedisRetryScan,
    RedisFindOpen,
    RedisFindInsert(char),
    RedisFindBackspace,
    RedisFindDelete,
    RedisFindConfirm,
    RedisFindCancel,
    RedisFindNext,
    RedisFindPrevious,
    RedisValueFilterFocus {
        tab_id: Uuid,
    },
    RedisValueFilterEdit(crate::model::text_input::TextInputEdit),
    RedisValueFilterPaste(String),
    RedisValueFilterSubmit,
    RedisValueFilterCancel,
    GridMove {
        rows: isize,
        columns: isize,
    },
    GridSelectRow(crate::model::tab::GridRowTarget),
    GridSelectColumn(crate::model::tab::GridColumnTarget),
    GridScrollRows {
        direction: isize,
        amount: crate::model::tab::GridScrollAmount,
    },
    GridAlignSelectedRow(crate::model::tab::GridRowAlignment),
    GridViewportChanged(crate::model::tab::DataGridViewport),
    OpenRecordView,
    RecordViewMoveFields(isize),
    RecordViewJumpFirstField,
    RecordViewJumpLastField,
    RecordViewMoveRow(isize),
    CloseRecordView,
    OpenTextDetail(crate::model::text_detail::TextDetailRequest),
    CopyTextDetailAll {
        session_id: Uuid,
    },
    CloseTextDetail,
    RecordViewViewportChanged {
        tab_id: Uuid,
        visible_fields: usize,
    },
    GridSelect {
        row: usize,
        column: usize,
    },
    ToggleResultView,
    WorkspaceSaveSucceeded {
        revision: u64,
    },
    WorkspaceSaveFailed {
        revision: u64,
        message: String,
        retryable: bool,
    },
    WorkspaceSaveFlushed {
        revision: u64,
    },
    WorkspaceSaveRetry,
    Quit,
}

impl Action {
    pub(crate) fn is_console_management_action(&self) -> bool {
        matches!(
            self,
            Self::NewConsole
                | Self::NewConsoleNamed(_)
                | Self::NewUnboundConsole
                | Self::NewUnboundConsoleNamed(_)
                | Self::OpenSqlEditorList
                | Self::SqlEditorListMove(_)
                | Self::SqlEditorListActivate
                | Self::SqlEditorListCreate
                | Self::SqlEditorListDeleteRequest
                | Self::SqlEditorListDeleteConfirm
                | Self::SqlEditorListDeleteActivate
                | Self::SqlEditorListDeleteCancel
                | Self::SqlEditorListDeleteFocusNext
                | Self::SqlEditorListDeleteFocusPrevious
                | Self::SqlEditorListSearchStart
                | Self::SqlEditorListRenameStart
                | Self::SqlEditorListRenameCommit
                | Self::SqlEditorListInputInsert(_)
                | Self::SqlEditorListInputBackspace
                | Self::SqlEditorListInputDeletePreviousWord
                | Self::SqlEditorListInputDeleteToStart
                | Self::SqlEditorListInputDelete
                | Self::SqlEditorListInputMoveLeft
                | Self::SqlEditorListInputMoveRight
                | Self::SqlEditorListInputMoveHome
                | Self::SqlEditorListInputMoveEnd
                | Self::SqlEditorListInputUndo
                | Self::SqlEditorListInputRedo
                | Self::SqlEditorListCancel
                | Self::ActivateSqlEditor(_)
        )
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CatalogEditorCursorTarget {
    SchemaField(usize),
    FormField(crate::model::catalog_editor::CatalogFormFocus),
    TableField(crate::model::catalog_editor::TableEditorFocus),
}

#[allow(clippy::large_enum_variant)]
#[derive(Clone, Debug)]
pub enum Command {
    PersistHelpPanelView(crate::config::HelpPanelView),
    LoadSqlHistory {
        overlay_id: Uuid,
        generation: u64,
        request: crate::persistence::sql_history::HistoryPageRequest,
    },
    TestProfile {
        request_id: u64,
        submission: ProfileSubmission,
    },
    DiscoverProfileCatalog {
        request_id: u64,
        submission: ProfileSubmission,
    },
    SaveProfile {
        request_id: u64,
        submission: ProfileSubmission,
        connect: bool,
    },
    DeleteProfile {
        request_id: u64,
        profile_id: Uuid,
    },
    UpdateProfileAccess {
        request_id: u64,
        profile_id: Uuid,
        change: ProfileAccessChange,
    },
    UpdateProfileOrganization {
        request_id: u64,
        mutation: ProfileOrganizationMutation,
    },
    Disconnect {
        connection: ConnectionIdentity,
    },
    Connect {
        profile_id: Uuid,
        generation: u64,
        target: ExecutionTarget,
    },
    LoadCatalogPage(CatalogRequest),
    DiscoverRedisDatabases {
        profile_id: Uuid,
        generation: u64,
    },
    ScanRedisKeys(crate::db::redis::types::KeyScanRequest),
    DeleteRedisKey {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        key: crate::db::redis::types::RedisKeyId,
    },
    DeleteRedisPrefix {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        target: crate::db::redis::types::RedisTarget,
        prefix: Vec<u8>,
    },
    DeleteRedisKeys {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        target: crate::db::redis::types::RedisTarget,
        keys: Vec<Vec<u8>>,
    },
    LoadRedisPreview {
        tab_id: Uuid,
        generation: u64,
        preview_generation: u64,
        key: crate::db::redis::types::RedisKeyId,
    },
    LoadRedisValuePage {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        preview_generation: u64,
        request: crate::db::redis::read::RedisReadRequest,
    },
    LoadRedisValuePreview {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        preview_generation: u64,
        key: crate::db::redis::types::RedisKeyId,
    },
    FormatLargeRedisValuePage {
        tab_id: Uuid,
        connection: ConnectionIdentity,
        preview_generation: u64,
        format: crate::value_preview::PreviewFormat,
        page: crate::db::redis::read::RedisValuePage,
    },
    PlanRedisMutation {
        request: crate::db::redis::mutation::RedisMutationRequest,
        operation: crate::db::redis::mutation::RedisMutationOperation,
        ttl: crate::db::redis::mutation::RedisTtlMutation,
        baseline: Option<crate::db::redis::mutation::RedisKeyBaseline>,
    },
    ExecuteRedisMutation(crate::db::redis::mutation::RedisMutationPlan),
    ResolveCatalogRelation {
        connection: ConnectionIdentity,
        catalog_epoch: u64,
        request_id: u64,
        relation: CatalogId,
        scope: CatalogScope,
    },
    ReconcileCatalogRelation {
        connection: ConnectionIdentity,
        old_relation: CatalogId,
        new_relation: CatalogId,
    },
    LoadCatalogObjectDefinition(CatalogObjectDefinitionRequest),
    LoadCatalogOwnerContext(CatalogOwnerContextRequest),
    SearchCatalog {
        owner: CatalogSearchOwner,
        request: CatalogSearchRequest,
    },
    CancelCatalogSearch {
        owner: CatalogSearchOwner,
        session_id: u64,
        generation: u64,
    },
    PlanCatalogDrop(CatalogDropRequest),
    PlanPrincipalDrop(crate::db::principal_drop::PrincipalDropRequest),
    PlanPrincipalMutation(crate::db::principal::PrincipalMutationRequest),
    ExecutePrincipalMutation(crate::db::principal::PrincipalMutationPlan),
    ExecutePrincipalDrop(crate::db::principal_drop::PrincipalDropPlan),
    ExecuteCatalogDrop(CatalogDropPlan),
    PlanCatalogMutation {
        request: CatalogMutationRequest,
        draft: crate::model::catalog_editor::CatalogDraft,
        baseline: Option<CatalogObjectDefinition>,
    },
    ExecuteCatalogMutation(CatalogMutationPlan),
    LoadRelationPreview(crate::model::relation::RelationRequest),
    LoadRelationDdl(crate::model::relation::RelationRequest),
    LoadPrincipals(crate::model::principal::PrincipalListRequest),
    LoadPrincipalDdl(crate::model::principal::PrincipalDdlRequest),
    LoadPrincipalDetails(crate::model::principal::PrincipalDetailsRequest),
    CancelPrincipalDdl(crate::model::principal::PrincipalDdlRequest),
    CancelRelationRequest(crate::model::relation::RelationRequest),
    RunQuery {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        generation: u64,
        sql: String,
    },
    LoadDashboardMetrics {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
    },
    LoadDashboardMetadata {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
    },
    LoadDashboardProcesses {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
    },
    CancelDashboardTasks {
        tab_id: Uuid,
        tab_generation: u64,
    },
    RunQueryPage {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        generation: u64,
        source_sql: String,
        dialect: crate::sql::SqlDialect,
        page: crate::model::pagination::PageRequest,
    },
    RunDerivedQuery {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        sql: String,
    },
    RunDerivedQueryPage {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        source_sql: String,
        where_clause: String,
        order_by_clause: String,
        dialect: crate::sql::SqlDialect,
        page: crate::model::pagination::PageRequest,
    },
    ManualBegin {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    ManualExecute {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        sql: String,
    },
    ManualExecutePage {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        source_sql: String,
        dialect: crate::sql::SqlDialect,
        count_sql: String,
        page: crate::model::pagination::PageRequest,
    },
    ManualCommit {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    ManualRollback {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    RelationMutation {
        request: crate::db::mutation::RelationMutationRequest,
    },
    RelationCommit {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    RelationRollback {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    CancelQuery {
        tab_id: Uuid,
        generation: u64,
    },
    CancelManual {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    PersistWorkspace {
        revision: u64,
        snapshot: crate::persistence::workspace::WorkspaceSnapshot,
    },
    FlushWorkspace {
        revision: u64,
    },
    ContinueWorkspaceSave,
    CompleteWorkspaceSave {
        revision: u64,
        succeeded: bool,
    },
    RetryWorkspaceSave,
    DeleteSqlFile(Uuid),
    WriteClipboard(ClipboardPayload),
    CheckSecretStoreAvailability,
    ScheduleCompletion(crate::sql::CompletionScheduleKey),
    ScheduleDiagnostics(crate::sql::DiagnosticScheduleKey),
    AnalyzeDiagnostics {
        key: crate::sql::DiagnosticScheduleKey,
        text: String,
        context: crate::sql::SemanticContext,
        catalog: crate::sql::CatalogSnapshot,
    },
    CheckForUpdate {
        request_id: u64,
        automatic: bool,
    },
    InstallUpdate {
        request_id: u64,
        channel: crate::update::UpdateChannel,
    },
    ScheduleUpdateCheck {
        delay_ms: u64,
    },
    Quit,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum CatalogSearchOwner {
    Explorer,
    Omni,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProfileOrganizationMutation {
    CreateGroup {
        id: Uuid,
        name: String,
    },
    RenameGroup {
        group_id: Uuid,
        name: String,
    },
    DeleteGroup {
        group_id: Uuid,
    },
    AssignProfile {
        profile_id: Uuid,
        group_id: Option<Uuid>,
    },
    MoveProfile {
        profile_id: Uuid,
        sibling_ids: Vec<Uuid>,
        direction: MoveDirection,
    },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProfileAccessChange {
    MakeGlobal,
    MakeProjectOnly(PathBuf),
    AddProject(PathBuf),
    RemoveProject(PathBuf),
}
